### PR TITLE
add updated PlaceTypes

### PR DESCRIPTION
**Pull request by treasuryoflives**
Add Regional House to PlaceTypes

### CODE REVIEW

**Review by rjyounes — CHANGES_REQUESTED** [review]
Katie, the serializer didn't get run on this file, and I've been generating it from the spreadsheet via TARQL. We can edit it manually from now on if you like, but we need to look at your precommit hook.

This and most other taxonomies will be editable via forms in the new editor.

**Comment by rjyounes** [comment]
I see you did update the CSV on the website, but you will need to commit that here as well.

**Comment by regularmike** [comment]
@rjyounes I will take a look at Katie's setup tomorrow. For now I have run it on my machine and I think the PR has been cleaned up now? Let me know.

**Review by rjyounes — APPROVED** [review]

**Comment by rjyounes** [comment]
Note that I moved the place type CSV here from the tol-data repo.

**Pull request merged**
